# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_CRYPTO_DEV_HFE)  += bst_hfe/
obj-$(CONFIG_CRYPTO_DEV_SKE)  += bst_ske/
obj-$(CONFIG_CRYPTO_DEV_PKE)  += bst_pke/
obj-$(CONFIG_CRYPTO_DEV_PKE)  += common/