obj-$(CONFIG_SND_BST_I2S) += bst_i2s.o

bst_i2s-y := bst-i2s.o
bst_i2s-$(CONFIG_SND_BST_PCM) += bst-pcm.o

obj-$(CONFIG_SND_BST_TDM) += bst_tdm.o

bst_tdm-y := bst-tdm.o
bst_tdm-$(CONFIG_SND_BST_PCM_TDM) += bst-pcm-tdm.o
