obj-$(CONFIG_VIDEO_BST_DEV) += \
    adi_des.o \
    camera.o \
    custom_camera.o \
    imx623_raw.o \
    max96724.o \
    max96726.o \
    ov2311_raw.o \
    ox03c_hil_yuv.o \
    ox03c_raw.o \
    ox03f_hil_yuv.o \
    ox03f_raw.o \
    ox08b_hil_yuv.o \
    ox08b_raw.o \
    utils.o

subdir-ccflags-y += -Wall
