# Makefile for LSI drivers
obj-$(CONFIG_ACP)			+= ncr.o
obj-$(CONFIG_ACP)			+= clocks.o
obj-$(CONFIG_LSI_NAND)			+= lsi_nand.o
obj-$(CONFIG_LSI_UBOOTENV)		+= ubootenv.o
obj-$(CONFIG_ACP)			+= version.o
obj-$(CONFIG_SERIAL_ACP)		+= serial.o
obj-$(CONFIG_ACP)			+= wrappers.o
obj-$(CONFIG_LSI_NET)			+= net.o
lsi_nand-objs := nand.o
