# SPEAR Platform Support
obj-$(CONFIG_SND_SPEAR_SOC) += spear_pcm.o
obj-$(CONFIG_SND_DESIGNWARE_I2S) += designware_i2s.o
obj-$(CONFIG_SND_SPEAR_SPDIF_IN) += spdif_in.o
obj-$(CONFIG_SND_SPEAR_SPDIF_OUT) += spdif_out.o

# SPEAR Machine Support
obj-$(CONFIG_SND_SPEAR_EVM) += spear_evb.o
