# SPDX-License-Identifier: GPL-2.0+
#
# Makefile for the Linux Bluetooth HCI device drivers.
#

obj-$(CONFIG_BST_IPC)	+= ipc_mailbox_controller.o
obj-$(CONFIG_BST_IPC)	+= ipc.o
obj-$(CONFIG_BST_IPC)	+= ipc_mempool.o
obj-$(CONFIG_BST_IPC)	+= ipc_communication_manager.o
obj-$(CONFIG_BST_IPC)	+= ipc_nodemanager.o
obj-$(CONFIG_BST_IPC)	+= ipc_session.o
obj-$(CONFIG_BST_IPC)	+= ipc_msg_manager.o
obj-$(CONFIG_BST_IPC)	+= ipc_sys.o
obj-$(CONFIG_BST_IPC)	+= ipc_common.o
obj-$(CONFIG_BST_IPC)	+= ipc_interface.o
obj-$(CONFIG_BST_IPC_STRESS)	+= ipc_stress.o
