#
# Makefile for the LTT objects.
#

obj-$(CONFIG_MARKERS)			+= ltt-channels.o
obj-$(CONFIG_LTT)			+= ltt-core.o
obj-$(CONFIG_LTT_TRACER)		+= ltt-tracer.o
obj-$(CONFIG_LTT_TRACE_CONTROL)		+= ltt-marker-control.o
obj-$(CONFIG_LTT_RELAY_LOCKED)		+= ltt-relay-locked.o
obj-$(CONFIG_LTT_RELAY_ALLOC)		+= ltt-relay-alloc.o
obj-$(CONFIG_LTT_SERIALIZE)		+= ltt-serialize.o
obj-$(CONFIG_LTT_STATEDUMP)		+= ltt-statedump.o
obj-$(CONFIG_LTT_FAST_SERIALIZE)	+= ltt-type-serializer.o
obj-$(CONFIG_LTT_TRACE_CONTROL)		+= ltt-trace-control.o
