ccflags-y +=  -I$(srctree)/drivers/bst_ipc_msgbx/include \
        -I$(srctree)/drivers/bst_ipc_msgbx/ipc_trans_layer/include \
        -I$(srctree)/drivers/bst_ipc_msgbx/ipc_app_layer/include
obj-y                          += st_public1_client.o
obj-y                          += thermalclient.o
obj-$(CONFIG_BST_THERMAL)      += bst_thermal.o
