# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux BST health_monitor device drivers.
#

obj-$(CONFIG_BST_HEALTH_MONITOR)	+= bst-health-monitor.o

bst-health-monitor-objs := health_monitor.o msgbox/safety-client/src-gen/healthmonitor_client.o msgbox/safety-client/src-gen/HealthmonitorClient.o

