# SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note OR MIT
#
# (C) COPYRIGHT 2019-2021 Arm Limited or its affiliates. All rights reserved.
#
#

obj-$(CONFIG_MALI_ARBITER_MODULES) := mali_arbiter.o

mali_arbiter-y := mali_arbiter_main.o mali_arbiter_sysfs.o


# Use our defines when compiling
ccflags-y += -I$(src)/../ptm/include
subdir-ccflags-y += -I$(src)/../ptm/include
