bst_hwcv-y = bst_hwcv_common.o bst_hwcv_gwarp.o bst_hwcv_scaler.o \
			 bst_hwcv_sys_manager.o bst_hwcv_mem_manager.o  bst_hwcv_irq_manager.o \
			 bst_hwcv_miscdev.o bst_hwcv_main.o bst_hwcv_dma_contig.o

obj-$(CONFIG_BST_HWCV) += bst_hwcv.o