/* SPDX-License-Identifier: GPL-2.0 */
/* clock driver for BST C1200
 * This file contains proprietary information that is the sole intellectual
 * property of Black Sesame Technologies, Inc. and its affiliates.
 * No portions of this material may be reproduced in any
 * form without the written permission of:
 * Black Sesame Technologies, Inc. and its affiliates
 * 2255 Martin Ave. Suite D
 * Santa Clara, CA 95050
 * Copyright @2016: all right reserved.
 */

#ifndef _CLOCK_BST_C1200_H
#define _CLOCK_BST_C1200_H

#define MAIN_OSC_CLK                                        (0)
#define LB_CPU1_MP4_DSU_CLK                                 (1)
#define LB_CPU1_MP4_CORE_CLK                                (2)
#define LB_CPU0_MP4_DSU_CLK                                 (3)
#define LB_CPU0_MP4_CORE_CLK                                (4)
#define LB_CPU1_MP4_PVT_SYS_CLK                             (5)
#define LB_CPU0_MP4_PVT_SYS_CLK                             (6)
#define LB_CPU_PERIP_CSTOPCLK                               (7)
#define LB_CPU_PERIP_CLK                                    (8)
#define LB_CPU_PERIP_SYSNOC_APB_PCLK                        (9)
#define LB_XGMAC_APB_S_PCLK                                 (10)
#define TOP_GTC_PCLK                                        (11)
#define LB_CPU_MP2_MASTER_ACLK                              (12)
#define LB_CPU_MP2_DB_NOC_PCLK                              (13)
#define LB_CPU_MP2_CS_PCLK                                  (14)
#define LB_CPU_MP2_DSU_CLK                                  (15)
#define LB_CPU_MP2_MP_ACLK                                  (16)
#define LB_CPU_MP2_CORE_CLK                                 (17)
#define MSGBX_SWITCH0_TO_CPU_GHCLK                          (18)
#define MSGBX_SWITCH0_TO_DB_GHCLK                           (19)

#define LB_GPU_G78AE_PVT_SYS_CLK                            (20)
#define LB_GPU_G78AE_TCU_WCLK                               (21)
#define LB_GPU_G78AE_AXI_S_ACLK                             (22)
#define LB_GPU_G78AE_ACE_M2_ACLK                            (23)
#define LB_GPU_G78AE_ACE_M1_ACLK                            (24)
#define LB_GPU_G78AE_ACE_M0_ACLK                            (25)
#define LB_GPU_G78AE_WCLK                                   (26)
#define LB_GPU_G78AE_SP_M_ACLK                              (27)
#define LB_GPU_G78AE_SP_PCLK                                (28)
#define LB_GPU_G78AE_SP_S_ACLK                              (29)

#define DDR0_PROBE_AXI_GACLK                                (30)
#define LB_LPDDR5_0_MAIN_CLK                                (31)
#define LB_LPDDR5_0_PCLK                                    (32)
#define LB_LPDDR5_0_S4_ACLK                                 (33)
#define LB_LPDDR5_0_S3_ACLK                                 (34)
#define LB_LPDDR5_0_S2_ACLK                                 (35)
#define LB_LPDDR5_0_S1_ACLK                                 (36)
#define LB_LPDDR5_0_S0_ACLK                                 (37)
#define LB_LPDDR5_1_MAIN_CLK                                (38)
#define LB_LPDDR5_1_PCLK                                    (39)
#define LB_LPDDR5_1_S4_ACLK                                 (40)
#define LB_LPDDR5_1_S3_ACLK                                 (41)
#define LB_LPDDR5_1_S2_ACLK                                 (42)
#define LB_LPDDR5_1_S1_ACLK                                 (43)
#define LB_LPDDR5_1_S0_ACLK                                 (44)

#define LB_SW_CSTOP_CLK                                     (45)
#define SYS_MAIN_CLK                                        (46)
#define LB_SW_PTP_CLK                                       (47)
#define SEC_SAFE_BLK_INST_ST_RGMII_RXCLK                    (48)
#define LB_RT_INTERNAL_GMII_TXCLK                           (49)
#define LB_SAFE_INTERNAL_GMII_TXCLK                         (50)
#define SWNOC_TO_RTNOC_GACLK                                (51)
#define RTNOC_TO_SWNOC_GACLK                                (52)
#define SWNOC_TO_SYSNOC_GACLK                               (53)
#define SAFENOC_TO_SWNOC_GACLK                              (54)
#define SOCNIC_S_TO_SWNOC_GACLK                             (55)
#define LB_XGMAC_AXIM_ACLK                                  (56)
#define MSGBX_SWITCH1_TO_SW_GHCLK                           (57)

#define LB_CS_DMA_HCLK                                      (58)
#define LB_CS_DMA_ACLK                                      (59)
#define LB_DB_DMA_HCLK                                      (60)
#define LB_DB_DMA_ACLK                                      (61)

#define LB_DISPLAY2_PCLK                                    (62)
#define LB_DISPLAY1_PCLK                                    (63)
#define LB_DISPLAY0_PCLK                                    (64)
#define LB_DISPLAY2_ACLK                                    (65)
#define LB_DISPLAY1_ACLK                                    (66)
#define LB_DISPLAY0_ACLK                                    (67)
#define LB_DISPLAY2_CH0_CLK                                 (68)
#define LB_DISPLAY1_CH1_CLK                                 (69)
#define LB_DISPLAY1_CH0_CLK                                 (70)
#define LB_DISPLAY0_CH1_CLK                                 (71)
#define LB_DISPLAY0_CH0_CLK                                 (72)

#define LB_PCIE_X4_MSTR_ACLK                                (73)
#define LB_PCIE_X2_MSTR_ACLK                                (74)
#define LB_PCIE_SLV_ACLK                                    (75)
#define LB_PCIE_DBI_ACLK                                    (76)
#define LB_PCIE_APB_PCLK                                    (77)
#define LB_PCIE_OSC_CLK                                     (78)
#define LB_PCIE_IST_ATSPEED_500M_CLK                        (79)
#define LB_PCIE_NOC_600M_CLK                                (80)

#define LB_USB_1_APB_PCLK                                   (81)
#define LB_USB_1_AXI_ACLK                                   (82)
#define LB_USB_1_REF_ALT_CLK                                (83)
#define LB_USB_0_APB_PCLK                                   (84)
#define LB_USB_0_AXI_ACLK                                   (85)
#define LB_USB_0_REF_ALT_CLK                                (86)

#define LB_SDEMMC1_S_HCLK                                   (87)
#define LB_SDEMMC1_M_HCLK                                   (88)
#define LB_SDEMMC1_W_BCLK                                   (89)
#define LB_SDEMMC0_S_HCLK                                   (90)
#define LB_SDEMMC1_S_PCLK                                   (91)
#define LB_SDEMMC0_S_PCLK                                   (92)
#define LB_SDEMMC0_M_HCLK                                   (93)
#define LB_SDEMMC0_W_BCLK                                   (94)
#define DUTYCYCLE_MONITOR_RANDCLK                           (95)

#define LB_UFS_REF_ALT_CLK                                  (96)
#define LB_UFS_APB_PCLK                                     (97)
#define LB_UFS_AXI_ACLK                                     (98)

#define I2SM_PLL0_OUT                                       (99)
#define I2SM_PLL1_OUT                                       (100)
#define LB_SOC_LSP1_APB_S0_PCLK                             (101)
#define LB_SOC_LSP0_APB_S0_PCLK                             (102)
#define LB_SOC_LSP1_IST_ATSPEED_25M_CLK                     (103)
#define LB_SOC_LSP0_IST_ATSPEED_25M_CLK                     (104)
#define LB_SOC_LSP1_WCLK                                    (105)
#define LB_SOC_LSP0_WCLK                                    (106)
#define LB_SOC_LSP1_UART_WCLK                               (107)
#define LB_SOC_LSP0_UART_WCLK                               (108)
#define LB_SOC_DMA_CORE_CLK                                 (109)
#define LB_SOC_DMA_HCLK                                     (110)
#define LB_SOC_DMA_ACLK                                     (111)
#define MSGBX_SWITCH0_TO_SOCDMA_GHCLK                       (112)

#define VIN_LLC                                             (113)
#define DSP3_IST_ATSPEED_25M_CLK                            (114)
#define DSP2_IST_ATSPEED_25M_CLK                            (115)
#define DSP1_IST_ATSPEED_25M_CLK                            (116)
#define DSP0_IST_ATSPEED_25M_CLK                            (117)
#define LB_CV_AXIS_CLK                                      (118)
#define LB_ISP_SCLK                                         (119)
#define LB_CV_DSP3_PBCLK                                    (120)
#define LB_CV_DSP2_PBCLK                                    (121)
#define LB_CV_DSP1_PBCLK                                    (122)
#define LB_CV_DSP0_PBCLK                                    (123)
#define LB_CV_CORE_CLK                                      (124)
#define LB_CV_AXIM1_CLK                                     (125)
#define LB_CV_AXIM0_CLK                                     (126)
#define LB_ISP_CV_MIPI_PVT_SYS_CLK                          (127)
#define LB_ISP_IST_ATSPEED_TEST_CLK                         (128)
#define LB_MIPI2_PHY_CFG_CLK                                (129)
#define LB_MIPI1_PHY_CFG_CLK                                (130)
#define LB_MIPI0_PHY_CFG_CLK                                (131)
#define LB_MIPI2_APB_CFG_PCLK                               (132)
#define LB_MIPI1_APB_CFG_PCLK                               (133)
#define LB_MIPI0_APB_CFG_PCLK                               (134)
#define MSGBX_SWITCH0_TO_ISPCV_GHCLK                        (135)

#define LB_SW_SB_SRAM_CLK                                   (136)
#define LB_STANDBY_APB_PCLK                                 (137)
#define CLK32K_IN                                           (138)
#define MCLK25M_IN                                          (139)

#define LB_NET_DSP_CLK                                      (140)
#define LB_NET_DSP_PBCLK                                    (141)
#define LB_NET_CLK                                          (142)
#define LB_NET_PVT_SYS_CLK                                  (143)
#define LB_NET_IST_ATSPEED_25M_CLK                          (144)
#define LB_NET_SAFETY_PCLK                                  (145)
#define MSGBX_SWITCH0_TO_NET_GHCLK                          (146)

#define LB_CDDEC1_WCLK                                      (147)
#define LB_CDDEC0_WCLK                                      (148)
#define LB_CDDEC1_PCLK                                      (149)
#define LB_CDDEC0_PCLK                                      (150)

#define LB_HIFI_DSP_XNNE_WCLK                               (151)
#define LB_HIFI_DSP_WCLK                                    (152)
#define LB_HIFI_DSP_CS_PBCLK                                (153)
#define LB_HIFI_DSP_CFG_PCLK                                (154)
#define LB_HIFI_DSP_S_ACLK                                  (155)
#define LB_HIFI_DSP_M_ACLK                                  (156)

#define DISPLAY_MUX0_PIXEL_CLK                              (157)
#define DISPLAY_MUX1_PIXEL_CLK                              (158)
#define DISPLAY_MUX2_PIXEL_CLK                              (159)
#define DISPLAY_MUX3_PIXEL_CLK                              (160)
#define DISPLAY_MUX4_PIXEL_CLK                              (161)
#define DISPLAY_MUX5_PIXEL_CLK                              (162)
#define LB_LVDS0_HSPEED_CLK                                 (163)
#define LB_LVDS1_HSPEED_CLK                                 (164)
#define LB_LVDS0_PCLK                                       (165)

#define LB_EDP_IPTEST_MAIN_CLK                              (166)
#define LB_EDP_IPTEST_JTAG_TCK                              (167)
#define LB_SOC_LSP1_I2S_M1_SCK                              (168)
#define LB_SOC_LSP1_I2S_M1_MCK                              (169)
#define LB_SOC_LSP1_SPDIF1_SCLK                             (170)
#define LB_EDP_PCLK                                         (171)
#define LB_EDP_ACLK                                         (172)
#define LB_EDP_CLK_800M                                     (173)
#define LB_EDP_SUSPEND_CLK                                  (174)
#define LB_EDP_REF_ALT_CLK                                  (175)

#define LB_DSI0_DPIPCLK                                     (176)
#define LB_DSI1_DPIPCLK                                     (177)
#define LB_DSI_CFG_REF_CLK                                  (178)
#define LB_DSI_PCLK                                         (179)
#define LB_DSI_CSITX_IPI_CLK                                (180)
#define LB_DSI1_CLKEXT                                      (181)
#define LB_DSI0_CLKEXT                                      (182)
#define LB_MEDIA_DMA_HCLK                                   (183)
#define LB_MEDIA_DMA_ACLK                                   (184)
#define LB_MIPI0_CLK_DATA                                   (185)
#define LB_MIPI1_CLK_DATA                                   (186)
#define LB_MIPI2_CLK_DATA                                   (187)

#define LB_RT_CSTOP_CLK                                     (188)
#define LB_SW_REALTIME_GMII_RXCLK                           (189)
#define LB_SGMAC_PTP_CLK                                    (190)
#define LB_REALTIME_SUBSYSTEM_IST_PCLK                      (191)
#define RTNOC_TO_SAFENOC_GACLK                              (192)
#define SAFENOC_TO_RTNOC_GACLK                              (193)
#define SECNOC_TO_RTNOC_GACLK                               (194)
#define MSGBX_SWITCH1_TO_REALTIME_GHCLK                     (195)

#define LB_SW_SUBSYSTEM_IST_PCLK                            (196)
#define TOP_IST_PCLK                                        (197)
#define SOC_IST_CLK                                         (198)
#define IST_DMA_CLK25M                                      SOC_IST_CLK
#define IST_STUCKAT_TEST_CLK                                (199)


#define CMN_GWCLK                                           (200)
#define BD_EXTERNAL_CLK_0                                   (201)
#define BD_EXTERNAL_CLK_1                                   (202)
#define BD_EXTERNAL_CLK_2                                   (203)
#define BD_EXTERNAL_CLK_3                                   (204)
#define BD_EXTERNAL_CLK_4                                   (205)
#define BD_EXTERNAL_CLK_5                                   (206)
#define BD_EXTERNAL_CLK_6                                   (207)
#define BD_EXTERNAL_CLK_7                                   (208)
#define LB_MATRIX_TOP_CRM_APB_PCLK                          (209)
#define TOPISTCTRL_TO_TOPCRM_PCLK                           (210)



#define LD_DMA_CORE_CLK                                     (211)
#define LD_DMA_CORE_CLK_GATE                                (212)
#define LD_DMA_AXI_CLK                                     	(213)
#define LD_DMA_AXI_CLK_GATE                                	(214)


#define LD_LSP0_UART0_WCLK                                  (215)
#define LD_LSP0_UART1_WCLK                                  (216)
#define LD_LSP1_UART2_WCLK                                  (217)
#define LD_LSP1_UART3_WCLK                                  (218)

#define LD_LSP0_UART0_WCLK_EN                                  (219)
#define LD_LSP0_UART1_WCLK_EN                                  (220)
#define LD_LSP1_UART2_WCLK_EN                                  (221)
#define LD_LSP1_UART3_WCLK_EN                                  (222)

#define LD_LSP0_UART0_PCLK                                  		(223)
#define LD_LSP0_UART1_PCLK                                  		(224)
#define LD_LSP1_UART2_PCLK                                  		(225)
#define LD_LSP1_UART3_PCLK                                  		(226)

#define LD_LSP0_UART0_PCLK_EN                                  		(227)
#define LD_LSP0_UART1_PCLK_EN                                  		(228)
#define LD_LSP1_UART2_PCLK_EN                                  		(229)
#define LD_LSP1_UART3_PCLK_EN                                  		(230)

#define LD_LSP0_GPIO0_PCLK_EN                                  		(231)
#define LD_LSP0_GPIO1_PCLK_EN                                  		(232)
#define LD_LSP0_GPIO2_PCLK_EN                                  		(233)
#define LD_LSP0_GPIO3_PCLK_EN                                  		(234)
#define LD_LSP1_GPIO4_PCLK_EN                                  		(235)
#define LD_LSP1_GPIO5_PCLK_EN                                  		(236)
#define LD_LSP1_GPIO6_PCLK_EN                                  		(237)
#define LD_LSP1_GPIO7_PCLK_EN                                  		(238)

#define LD_LSP0_GPIO0_PCLK                                  		(239)
#define LD_LSP0_GPIO1_PCLK                                  		(240)
#define LD_LSP0_GPIO2_PCLK                                  		(241)
#define LD_LSP0_GPIO3_PCLK                                  		(242)
#define LD_LSP1_GPIO4_PCLK                                  		(243)
#define LD_LSP1_GPIO5_PCLK                                  		(244)
#define LD_LSP1_GPIO6_PCLK                                  		(245)
#define LD_LSP1_GPIO7_PCLK                                  		(246)


#define LD_LSP0_WDT0_WCLK                                  			(247)
#define LD_LSP0_WDT0_PCLK                                  			(248)
#define LD_LSP0_WDT1_WCLK                                  			(249)
#define LD_LSP0_WDT1_PCLK                                  			(250)
#define LD_LSP1_WDT2_WCLK                                  			(251)
#define LD_LSP1_WDT2_PCLK                                  			(252)
#define LD_LSP1_WDT3_WCLK                                  			(253)
#define LD_LSP1_WDT3_PCLK                                  			(254)

#define LD_LSP0_WDT0_WCLK_EN                                  		(255)
#define LD_LSP0_WDT0_PCLK_EN                                  		(256)
#define LD_LSP0_WDT1_WCLK_EN                                  		(257)
#define LD_LSP0_WDT1_PCLK_EN                                  		(258)
#define LD_LSP1_WDT2_WCLK_EN                                  		(259)
#define LD_LSP1_WDT2_PCLK_EN                                  		(260)
#define LD_LSP1_WDT3_WCLK_EN                                  		(261)
#define LD_LSP1_WDT3_PCLK_EN                                  		(262)


#define LD_LSP0_TIMER0_WCLK_EN                                  		(263)
#define LD_LSP0_TIMER1_WCLK_EN                                  		(264)
#define LD_LSP0_TIMER2_WCLK_EN                                  		(265)
#define LD_LSP0_TIMER3_WCLK_EN                                  		(266)
#define LD_LSP0_TIMER4_WCLK_EN                                  		(267)
#define LD_LSP0_TIMER5_WCLK_EN                                  		(268)
#define LD_LSP0_TIMER6_WCLK_EN                                  		(269)
#define LD_LSP0_TIMER7_WCLK_EN                                  		(270)
#define LD_LSP0_TIMER_PCLK_EN                                  		    (271)

#define LD_LSP1_TIMER0_WCLK_EN                                  		(272)
#define LD_LSP1_TIMER1_WCLK_EN                                  		(273)
#define LD_LSP1_TIMER2_WCLK_EN                                  		(274)
#define LD_LSP1_TIMER3_WCLK_EN                                  		(275)
#define LD_LSP1_TIMER4_WCLK_EN                                  		(276)
#define LD_LSP1_TIMER5_WCLK_EN                                  		(277)
#define LD_LSP1_TIMER6_WCLK_EN                                  		(278)
#define LD_LSP1_TIMER7_WCLK_EN                                  		(279)
#define LD_LSP1_TIMER_PCLK_EN                                  		    (280)


#define LD_LSP0_TIMER0_WCLK                                  		(281)
#define LD_LSP0_TIMER1_WCLK                                  		(282)
#define LD_LSP0_TIMER2_WCLK                                  		(283)
#define LD_LSP0_TIMER3_WCLK                                  		(284)
#define LD_LSP0_TIMER4_WCLK                                  		(285)
#define LD_LSP0_TIMER5_WCLK                                  		(286)
#define LD_LSP0_TIMER6_WCLK                                  		(287)
#define LD_LSP0_TIMER7_WCLK                                  		(288)
#define LD_LSP0_TIMER_PCLK                                 		    (289)

#define LD_LSP1_TIMER0_WCLK                                  		(290)
#define LD_LSP1_TIMER1_WCLK                                  		(291)
#define LD_LSP1_TIMER2_WCLK                                  		(292)
#define LD_LSP1_TIMER3_WCLK                                  		(293)
#define LD_LSP1_TIMER4_WCLK                                  		(294)
#define LD_LSP1_TIMER5_WCLK                                  		(295)
#define LD_LSP1_TIMER6_WCLK                                  		(296)
#define LD_LSP1_TIMER7_WCLK                                  		(297)
#define LD_LSP1_TIMER_PCLK                                  		(298)



#define LD_LSP0_SMBUS0_WCLK                                  		(299)
#define LD_LSP0_SMBUS0_PCLK                                  		(301)
#define LD_LSP0_SMBUS1_WCLK                                  		(302)
#define LD_LSP0_SMBUS1_PCLK                                  		(303)
#define LD_LSP1_SMBUS2_WCLK                                  		(304)
#define LD_LSP1_SMBUS2_PCLK                                  		(305)
#define LD_LSP1_SMBUS3_WCLK                                  		(306)
#define LD_LSP1_SMBUS3_PCLK                                  		(307)


#define LD_LSP0_SMBUS0_WCLK_EN                                  		(308)
#define LD_LSP0_SMBUS0_PCLK_EN                                  		(309)
#define LD_LSP0_SMBUS1_WCLK_EN                                  		(310)
#define LD_LSP0_SMBUS1_PCLK_EN                                  		(311)
#define LD_LSP1_SMBUS2_WCLK_EN                                  		(312)
#define LD_LSP1_SMBUS2_PCLK_EN                                  		(313)
#define LD_LSP1_SMBUS3_WCLK_EN                                  		(314)
#define LD_LSP1_SMBUS3_PCLK_EN                                  		(315)

#define LD_LSP0_I2C0_WCLK                                               (316)           
#define LD_LSP0_I2C0_PCLK                                               (317)
#define LD_LSP0_I2C1_WCLK                                               (318)
#define LD_LSP0_I2C1_PCLK                                               (319)
#define LD_LSP0_I2C2_WCLK                                               (320)
#define LD_LSP0_I2C2_PCLK                                               (321)
#define LD_LSP0_I2C3_WCLK                                               (322)
#define LD_LSP0_I2C3_PCLK                                               (323)
#define LD_LSP1_I2C4_WCLK                                               (324) 
#define LD_LSP1_I2C4_PCLK                                               (325)
#define LD_LSP1_I2C5_WCLK                                               (326)
#define LD_LSP1_I2C5_PCLK                                               (327)
#define LD_LSP1_I2C6_WCLK                                               (328)
#define LD_LSP1_I2C6_PCLK                                               (329)
#define LD_LSP1_I2C7_WCLK                                               (330)
#define LD_LSP1_I2C7_PCLK                                               (331)

#define LD_LSP0_I2C0_WCLK_EN                                               (332)           
#define LD_LSP0_I2C0_PCLK_EN                                               (333)
#define LD_LSP0_I2C1_WCLK_EN                                               (334)
#define LD_LSP0_I2C1_PCLK_EN                                               (335)
#define LD_LSP0_I2C2_WCLK_EN                                               (336)
#define LD_LSP0_I2C2_PCLK_EN                                               (337)
#define LD_LSP0_I2C3_WCLK_EN                                               (338)
#define LD_LSP0_I2C3_PCLK_EN                                               (339)
#define LD_LSP1_I2C4_WCLK_EN                                               (340) 
#define LD_LSP1_I2C4_PCLK_EN                                               (341)
#define LD_LSP1_I2C5_WCLK_EN                                               (342)
#define LD_LSP1_I2C5_PCLK_EN                                               (343)
#define LD_LSP1_I2C6_WCLK_EN                                               (344)
#define LD_LSP1_I2C6_PCLK_EN                                               (345)
#define LD_LSP1_I2C7_WCLK_EN                                               (346)
#define LD_LSP1_I2C7_PCLK_EN                                               (347)





#define LD_LSP0_SPI0_M_WCLK                                                (348)
#define LD_LSP0_SPI0_M_PCLK                                                (349)
#define LD_LSP0_SPI1_S_WCLK                                                (350)
#define LD_LSP0_SPI1_S_PCLK                                                (351)
#define LD_LSP1_SPI0_M_WCLK                                                (352)
#define LD_LSP1_SPI0_M_PCLK                                                (353)
#define LD_LSP1_SPI1_S_WCLK                                                (354)
#define LD_LSP1_SPI1_S_PCLK                                                (355)


#define LD_LSP0_SPI0_M_WCLK_EN                                             (356)
#define LD_LSP0_SPI0_M_PCLK_EN                                             (357)
#define LD_LSP0_SPI1_S_WCLK_EN                                             (358)
#define LD_LSP0_SPI1_S_PCLK_EN                                             (359)
#define LD_LSP1_SPI0_M_WCLK_EN                                             (360)
#define LD_LSP1_SPI0_M_PCLK_EN                                             (361)
#define LD_LSP1_SPI1_S_WCLK_EN                                             (362)
#define LD_LSP1_SPI1_S_PCLK_EN                                             (363)




#define LD_USB0_RCLK                                                   (364)
#define LD_USB0_U2PHYREF                                               (365)
#define LD_USB0_U3PHYREF                                               (366)
#define LD_USB0_ACLK                                                   (367)
#define LD_USB0_PCLK                                                   (368)
#define LD_USB1_RCLK                                                   (369)
#define LD_USB1_U2PHYREF                                               (370)
#define LD_USB1_U3PHYREF                                               (371)
#define LD_USB1_ACLK                                                   (372)
#define LD_USB1_PCLK                                                   (373)

#define LD_USB0_RCLK_EN                                                (374)
#define LD_USB0_U2PHYREF_EN                                               (375)
#define LD_USB0_U3PHYREF_EN                                               (376)
#define LD_USB0_ACLK_EN                                                   (377)
#define LD_USB0_PCLK_EN                                                   (378)
#define LD_USB1_RCLK_EN                                                   (379)
#define LD_USB1_U2PHYREF_EN                                               (380)
#define LD_USB1_U3PHYREF_EN                                               (381)
#define LD_USB1_ACLK_EN                                                   (382)
#define LD_USB1_PCLK_EN                                                   (383)


#define LD_PLL_DISPLAY0                                              (384)
#define LD_PLL_DISPLAY1                                              (385)
#define LD_PLL_DISPLAY2                                              (386)
#define LD_PLL_DISPLAY3                                              (387)

#define LD_PLL_DISPLAY0_SEL                                              (388)
#define LD_PLL_DISPLAY1_SEL                                              (389)
#define LD_PLL_DISPLAY2_SEL                                              (390)
#define LD_PLL_DISPLAY3_SEL                                              (391)

#define LD_PLL_DISPLAY_MUX0                                              (392)
#define LD_PLL_DISPLAY_MUX1                                              (393)
#define LD_PLL_DISPLAY_MUX2                                              (394)
#define LD_PLL_DISPLAY_MUX3                                              (395)
#define LD_PLL_DISPLAY_MUX4                                              (396)


#define LD_PLL_DISPLAY0_FRAC_DIV                                              (397)
#define LD_PLL_DISPLAY1_FRAC_DIV                                              (398)
#define LD_PLL_DISPLAY2_FRAC_DIV                                              (399)
#define LD_PLL_DISPLAY3_FRAC_DIV                                              (400)

#define LD_PLL_DISPLAY0_CH0_EN                                             (401)
#define LD_PLL_DISPLAY0_CH1_EN                                             (402)
#define LD_PLL_DISPLAY1_CH0_EN                                             (403)
#define LD_PLL_DISPLAY1_CH1_EN                                             (404)
#define LD_PLL_DISPLAY2_CH0_EN                                             (405)

#define LB_PLL_SDEMMC0_M_HCLK                                                (406)
#define LB_PLL_SDEMMC0_W_BCLK                                              (407)
#define LB_PLL_SDEMMC1_M_HCLK                                                (408)
#define LB_PLL_SDEMMC1_W_BCLK                                              (409)

#define LB_PLL_SDEMMC0_M_HCLK_EN                                              (410)
#define LB_PLL_SDEMMC0_W_BCLK_EN                                              (411)
#define LB_PLL_SDEMMC1_M_HCLK_EN                                              (412)
#define LB_PLL_SDEMMC1_W_BCLK_EN                                              (413)

#define LP_GPU_TCU_WCLK                                                       (414)
#define LP_GPU_WCLK                                                           (415)
#define LP_GPU_SP_M_WCLK                                                      (416)
#define LP_GPU_SP_PCLK                                                        (417)

#define LP_GPU_TCU_WCLK_EN                                                       (418)
#define LP_GPU_WCLK_EN                                                           (419)
#define LP_GPU_SP_M_WCLK_EN                                                      (420)
#define LP_GPU_SP_PCLK_EN                                                        (421)


#define CLK_MAX                                             (422)




#endif /* _CLOCK_BST_C1200_H */
