/* SPDX-License-Identifier: GPL-2.0-only OR BSD-3-Clause */
/*
 * Copyright 2020-2023 NXP
 */

#ifndef __DT_BINDINGS_SCMI_CLOCK_S32CC_H
#define __DT_BINDINGS_SCMI_CLOCK_S32CC_H

#define S32CC_SCMI_COMPLEX_CLK			0xFFFFFFFFU
#define S32CC_SCMI_NOT_IMPLEMENTED_CLK	0xFFFFFFFEU

#define S32CC_SCMI_CLK_BASE_ID			0U
#define S32CC_SCMI_CLK(N)				((N) + S32CC_SCMI_CLK_BASE_ID)

#define S32CC_SCMI_CLK_VERSION_MAJOR	(1)
#define S32CC_SCMI_CLK_VERSION_MINOR	(0)

/* A53 */
#define S32CC_SCMI_CLK_A53				S32CC_SCMI_CLK(0)
/* LINFlexD */
#define S32CC_SCMI_CLK_LINFLEX_XBAR		S32CC_SCMI_CLK(13)
#define S32CC_SCMI_CLK_LINFLEX_LIN		S32CC_SCMI_CLK(14)

#define S32CC_SCMI_PLAT_CLK_BASE_ID		S32CC_SCMI_CLK(94)

#define S32CC_SCMI_CLK_MAX_ID			S32CC_PLAT_SCMI_CLK(33)

#endif /* __DT_BINDINGS_SCMI_CLOCK_S32CC_H */
