# SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note OR MIT
#
# (C) COPYRIGHT 2019-2021 ARM Limited. All rights reserved.
#
# This program is free software and is provided to you under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation, and any use by you of this program is subject to the terms
# of such GNU license.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, you can access it online at
# http://www.gnu.org/licenses/gpl-2.0.html.
#
#
obj-$(CONFIG_MALI_GPU_POWER_MODULES) += mali_gpu_power/
obj-$(CONFIG_MALI_ARBITER_MODULES) += mali_arbiter/
obj-$(CONFIG_MALI_ARBITER_MODULES) += mali_emu_kbase/
obj-$(CONFIG_MALI_XEN) += mali_arbiter/mali_arbif_xenback/
obj-$(CONFIG_MALI_XEN) += xen/mali_arbif_xenfront/
obj-$(CONFIG_MALI_PARTITION_MANAGER) += ptm/

INCLUDES = \
        -I$(src) \
        -I$(src)/include \
        -I$(src)/mali_arbiter \
        -I$(src)/../arbiter


ccflags-y += $(INCLUDES)
subdir-ccflags-y += $(INCLUDES)