# SPDX-License-Identifier: GPL-2.0
#
# Makefile for bst msgbx trans
#
ccflags-y += -I$(srctree)/drivers/bst_ipc_msgbx/include \
	-I$(srctree)/drivers/bst_ipc_msgbx/ipc_hw_layer/include -I$(srctree)/drivers/bst_ipc_msgbx/ipc_trans_layer/include
obj-y += ipc_trans_buffer.o ipc_trans_cfg.o
obj-y += ipc_trans_msg_mgt.o ipc_trans_routing.o
obj-y += ipc_trans_runtime.o ipc_trans_ses_mgt.o ipc_trans_sts_mgt.o ipc_trans_utl.o


