# SPDX-License-Identifier: GPL-2.0
#
# Makefile for bst msgbx hw
#
ccflags-y += -I$(srctree)/drivers/bst_ipc_msgbx/ipc_app_layer/posix/include -I$(srctree)/drivers/bst_ipc_msgbx/include \
	-I$(srctree)/drivers/bst_ipc_msgbx/ipc_trans_layer/include
#obj-y += test_server.o server.o
obj-y += test_client.o

