#
# Makefile for the Freescale Ethernet controllers
#
EXTRA_CFLAGS           += -DVERSION=\"\"
#
#Include netcomm SW specific definitions
include $(srctree)/drivers/net/dpa/NetCommSw/ncsw_config.mk
#
obj-y		+= modules/integrations/P4080/FM/
obj-y		+= system/
obj-y		+= util/
obj-y		+= wrappers/Peripherals/FM/
obj-y		+= xx/
