#
# 2.6 makefile for T2/3 SEC2.x legacy interface module
#

#EXTRA_CFLAGS += -DSEC2_DBG_INFO -DSEC2_DBG_EXTENDED_ERROR
EXTRA_CFLAGS += -DSEC2_DBG_INFO

obj-$(CONFIG_CRYPTO_DEV_EXTENS_T23X_SEC2) += t23xsec2.o

t23xsec2-objs := t23xsec2core.o t2dpd.o sec2_sctrMap.o t23xsec2mod.o
