# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_AXXIA) += \
	axm5516-amarillo.dtb
dtb-$(CONFIG_ARCH_AXXIA) += \
	axm5516-amarillo.dtb \
	axm5504-sim-mmc.dtb \
	axm5504-sim-virtio.dtb \
	axm5516-sim-mmc.dtb \
	axm5516-sim-virtio.dtb \
	axm5504-emu.dtb \
	axm5507-emu.dtb \
	axm5512-amarillo.dtb \
	axm5508-amarillo.dtb
