# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux Kernel bst ipc msgbox specific device drivers.
#
obj-$(CONFIG_BST_IPC_MSGBX)	+= ipc_hw_layer/
obj-$(CONFIG_BST_IPC_MSGBX)	+= ipc_trans_layer/
obj-$(CONFIG_BST_IPC_MSGBX)	+= ipc_app_layer/