# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux BST fusa_inject device drivers.
#

obj-$(CONFIG_BST_FUSA_INJECT) := error_inject.o msgbox/safety-client/src-gen/safetylib_client.o msgbox/safety-client/src-gen/safetylibClient.o

