// SPDX-License-Identifier: GPL-2.0+
/*
 *  Copyright (C) 2024 Black Sesame Technologies. All Rights Reserved.
 */
 
#define  SDHCI_CLOCK_PLL_EN	0x0008
/*
 * configure clk by dts
 */
#define SDHCI_QUIRK2_CLK_FROM_DTS			(1<<18)
/*
 * Controller does not support mmc 3.3v
 */
#define SDHCI_QUIRK2_MMC_NO_3_3V			(1<<19)
#define SDHCI_TUNING_COUNT  32

#define SOC_PMM_REG_BASEADDR                    0x30001000
#define SC_PMM_REG_OFFSET(n)                    (0x04*n)

#define LOCAL_RST_CFG  							0x00
#define CLK_GATE_CFG 							0x04
#define SDEMMC_CRM_BCLK_DIV_CTRL 				0x08
#define SDEMMC_CRM_RX_CLK_CTRL                  0X14
#define SDEMMC_CRM_TIMER_DIV_CTRL 				0x0C
#define SDEMMC_CRM_CQE_CLK_DIV_CTRL 			0x10
#define SDEMMC_CRM_ECC_STATUS 					0x18
#define SDEMMC_CRM_VOL_CTRL 					0x1C
#define SDEMMC_CRM_LED_CTRL 					0x20
#define SDEMMC_CRM_PARITY                       0x24
#define SDEMMC_CRM_FREQ_CHECK_EN                0x28
#define SDEMMC_CRM_RREQ_INTR                    0x2c
#define SDEMMC_CRM_TXCLK_FREQ_REF_CLKCNT        0x30
#define SDEMMC_CRM_TXCLK_RREQ_HIGHCLKCNT        0x34
#define SDEMMC_CRM_TXCLK_RREQ_THRESHOLD         0x38
#define SDEMMC_CRM_TXCLK_RREQ_HIGHCLK_PPM       0x3c
#define SDEMMC_CRM_RXCLK_RREQ_REF_CLKCNT        0x40
#define SDEMMC_CRM_RXCLK_RREQ_HIGHCLKCNT        0x44
#define SDEMMC_CRM_RXCLK_RREQ_THRESHOLD         0x48
#define SDEMMC_CRM_RXCLK_RREQ_HIGHCLK_PPM       0x4c
#define SDEMMC_CRM_TIMERCLK_RREQ_REF_CLKCNT     0x50
#define SDEMMC_CRM_TIMERCLK_RREQ_HIGHCLKCNT     0x54
#define SDEMMC_CRM_TIMERCLK_RREQ_THRESHOLD      0x58
#define SDEMMC_CRM_TIMERCLK_RREQ_HIGHCLK_PPM    0x5c
#define SDEMMC_CRM_CQECLK_RREQ_REF_CLKCNT       0x60
#define SDEMMC_CRM_CQECLK_RREQ_HIGHCLKCNT       0x64
#define SDEMMC_CRM_CQECLK_RREQ_THRESHOLD        0x68
#define SDEMMC_CRM_CQECLK_RREQ_HIGHCLK_PPM      0x6c
#define SDEMMC_CRM_BCLK_RREQ_REF_CLKCNT         0x70
#define SDEMMC_CRM_BCLK_RREQ_HIGHCLKCNT         0x74
#define SDEMMC_CRM_BCLK_RREQ_THRESHOLD          0x78
#define SDEMMC_CRM_BCLK_RREQ_HIGHCLK_PPM        0x7c
#define SDEMMC_CRM_REG_WR_PROTECT        		0x88
#define SDEMMC_CRM_INJECT_CSR        			0x8c
#define SDEMMC_CRM_SDEMMC_CSR_PARITY_CTRL   	0x90
#define SDEMMC_CRM_DELAY_CHAIN_SEL			   	0x94
#define SDEMMC_CRM_SDEMMC_CFG0			   		0x100

#define SDEMMC_CRM_REG_WR_PROTECT_MAGIC 0xABCD1234