# SPDX-License-Identifier: GPL-2.0+
#
# Makefile for the Linux Kernel bst flexcan specific device drivers.
#

obj-y                           += bst_vcan.o
obj-y                           += switch0_can_gateway_client.o
obj-y                           += adas5_can_gateway_client.o