#!/bin/sh

#  (kgit-pull), (git-pull wrapper)

#  Copyright (c) 2008-2009 Wind River Systems, Inc.

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License version 2 as
#  published by the Free Software Foundation.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#  See the GNU General Public License for more details.

#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

# For consistent behaviour with "grep -w"
LC_ALL=C
export LC_ALL

usage()
{
cat <<EOF

 kgit-pull <upstream>

  Very simple wrapper around git pull. Placeholder script, feel
  free to NOT use this.

   -h: help
   -v: verbose

EOF
}

if [ ! $# -gt 0 ]; then
    usage
    exit
fi

while [ $# -gt 0 ]; do
	case "$1" in
                -h|--h)
                        usage
                        exit
                        ;;
		*)
			break
			;;
	esac
	shift
done

upstream=$1

if [ -z "$upstream" ]; then
    usage
    exit 1
fi

path=`dirname $0`
. $path/kgit

git pull $@
