#!/bin/bash

#  (kgit-init), (initialize a Wind River kernel git tree)

#  Copyright (c) 2008-2010 Wind River Systems, Inc.

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License version 2 as
#  published by the Free Software Foundation.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#  See the GNU General Public License for more details.

#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

# For consistent behaviour with "grep -w"
LC_ALL=C
export LC_ALL

path=`dirname $0`
. $path/kgit

install_resources()
{
    # look in our directory for:
    #   kgit-*
    #   guilt-*
    #   generate_cfg, kconf_check, configme

    ls $path/kgit-* &> /dev/null
    if [ $? -eq 0 ]; then
	tools=`echo "$tools"; ls $path/kgit-*; ls $path/kgit`
    fi
    ls $path/guilt-* &> /dev/null
    if [ $? -eq 0 ]; then
	tools=`echo "$tools"; ls $path/guilt-*`
    fi
    if [ -e $path/scc ]; then
	tools=`echo "$tools"; echo "$path/scc"`
    fi
    if [ -e $path/generate_cfg ]; then
	tools=`echo "$tools"; echo "$path/generate_cfg"`
    fi
    if [ -e $path/kconf_check ]; then
	tools=`echo "$tools";  echo "$path/kconf_check"`
    fi
    if [ -e $path/kconf_check ]; then
	tools=`echo "$tools";  echo "$path/configme"`
    fi
    
    if [ -n "$tools" ]; then
	mkdir -p $wrs_dir/scripts
	for s in $tools; do
 	    cp $s $wrs_dir/scripts
	done
    fi
}

# make sure you are in the target repo when calling this
clean_tgt_repo()
{
    if [ -n "$verbose" ]; then
	echo "[INFO] cleaning base clone"
    fi

    if [ -d .git ]; then
	# Keep tags that came from kernel.org; delete the rest, i.e.
	# v2.6.nn and v2.6.nn-rcM and v2.6.nn.M (nn=10,11, ..99, M=0,1, ...99)
	for tg in `git tag| grep -v 'v2.6.[0-9]\{2\}\(\(-rc[0-9]\{1,2\}\)\{0,1\}$\|\.[0-9]\{1,2\}$\)'`
	do
	    git tag -d $tg > /dev/null
	done

	# We've come here without an active checkout, on what was a bare
	# clone, so manually make sure we are on master. We should be on
	# master anyway, but make sure, otherwise we won't be able to
	# delete whatever branch we are on.
	echo 'ref: refs/heads/master' > .git/HEAD
	for br in `git branch | grep -v '\* master$'`
	do
	    git branch -D $br > /dev/null
	done
    fi
}

usage()
{
cat <<EOF

 kgit-init [-v] [-m <commit message>] 
           [-c] [--reference <repo>]
           [-t <initial tag>] <src> [<base_branch>] <tgt_repo>
 
  Initialize an existing or new repository

   -m: the initial commit message to use when creating the repo
   -t: tag to apply to the repository during creation
   -c: clean the tgt_repo after the clone completes. This will
       perform garbage collection and remove all existing 
       branches (under the assumption they'll be recreated)
   --reference <repo>: repo to use as the reference during clone

   <src>        : The source repository.
   <base branch>: optional. indicates a base branch point in the
                  src repository to use as the base for the
                  dest repository
   <tgt_rep>    : repository to initialize. Can exist or not
                  exist before the command is run.

   -h: help
   -v: verbose

EOF
}

# command line processing
while [ $# -gt 0 ]; do
    case "$1" in
	-b|--b)
		cmdline_branch="$2"
		shift
		;;
	-m|--m)
		message="$2"
		shift
		;;
	-o|--o)
		dest="$2"
		shift
		;;
	--reference)
		reference="$2"
		shift
		;;
	-v|--v)
		verbose=t
		;;
	-c|--c)
		clean=t
		;;
	-h|--h) 
	        usage
                exit;
                ;;
	*)
	        break
		;;
    esac
    shift
done

if [ ! $# -gt 0 ]; then
    usage
    exit
fi

# blindly guess that everything was passed
src=$1
base_branch=$2
dest=$3

# now fixup based on zero'd values
if [ -z "$base_branch" ]; then
    # no source, no branch, just a dest. We'll be
    # reanimating this repo
    dest=$src
    src=
else
    if [ -z "$dest" ]; then
	# no branch was passed, this is just <src> <dest>
	dest=$base_branch
	base_branch=
    fi
fi

if [ -n "$dest" ] && [ -z "$src" ]; then
    if [ ! -d "$dest" ]; then
	echo "ERROR. If no src is passed, $dest must exist"
	exit 1
    fi
fi  

if [ -z "$src" ] && [ ! -d "$src" ]; then
    echo "ERROR. $src is not a valid src repository"
    exit 1
fi

if [ -z "$message" ]; then
    message="WR Linux baseline"
fi

# figure out what type of type destination repository we are creating
new_repo=
existing_but_not_wrs_repo=
existing_repo=
if [ -d "$dest/.git" ]; then
    x=`cd $dest; git show-ref wrs_base`
    if [ -n "$x" ]; then
	existing_repo=t
    else
	existing_but_not_wrs_repo=t
    fi
else
    # this means we are starting a repository from scratch
    new_repo=t
fi

if [ -n "$new_repo" ]; then
    if [ -z "$src" ]; then
	if [ -n "$verbose" ]; then
	    echo "[INFO] Initializing git repository";
	fi
	mkdir -p $dest
	(cd $dest; git init -q)
    else
	if [ -n "$verbose" ]; then
	    echo "[INFO] git clone --shared $src $dest"
	else
	    clone_opt=-q
	fi

	# optimize for local src
	if [ -d "$src" ]; then
	    mkdir -p $dest

	    # check to see if a reference was passed, and we don't need
	    # shared in this case
	    if [ -n "$reference" ]; then
		if [ -d "$reference" ]; then
		    clone_opt="$clone_opt --reference $reference"
		fi
	    else
		clone_opt="$clone_opt --shared"
	    fi

	    # this means that we don't have to worry about converting
	    # remote branches into local tracking ones
	    git clone --bare $clone_opt $src $dest/.git
	    r=$?
	    if [ $r -ne 0 ]; then
		echo [ERROR] git clone of \"$src\" failed
		exit $r
	    fi

	    # check to see if the src is a bare repository and if
	    # it is, do an optimized startup
	    if [ -d $src/.git ]; then
		cp -a $src/.git/config $dest/.git
		cd $dest
	    else
		cd $dest
		git config core.bare false
	    fi

	    if [ -n "$clean" ]; then
		clean_tgt_repo
	    fi

	    git remote add origin $src
		
	    # check to see if there is already a wrs_base branch
	    git show-ref --quiet --verify -- "refs/heads/wrs_base";
	    if [ $? -eq 1 ]; then
		if [ -n "$verbose" ]; then
		    echo "[INFO] creating branch wrs_base from $base_branch";
		else
		    checkout_opts=-q
		fi
		git checkout -f $checkout_opts -b wrs_base $base_branch
		r=$?
		if [ $r -ne 0 ]; then
		    echo [ERROR] git checkout of \"$base_branch\" failed
		    exit $r
		fi
	    else
		# change the type of repo ...
		git checkout -f wrs_base
		existing_repo=t
		new_repo=
		existing_but_not_wrs_repo=
	    fi
	else
	    git clone $clone_opt $src $dest
	    r=$?
	    if [ $r -ne 0 ]; then
		echo [ERROR] git clone of \"$src\" failed
		exit $r
	    fi
	    cd $dest

	    if [ -n "$clean" ]; then
		clean_tgt_repo
	    fi

	    git show-ref --quiet --verify -- "refs/heads/wrs_base";
	    if [ $? -eq 1 ]; then
		if [ -n "$verbose" ]; then
		    echo "[INFO] creating branch wrs_base from $base_branch";
		else
		    checkout_opts=-q
		fi
		git checkout $checkout_opts -b wrs_base $base_branch
	    else
		# change the type of repo ...
		git checkout wrs_base
		existing_repo=t
	    fi
	fi
    fi
fi

if [ -n "$new_repo" ] || [ -n "$existing_but_not_wrs_repo" ]; then
    if [ ! -d "wrs/cfg/meta/obj" ]; then
	mkdir -p wrs/cfg/meta/obj
    fi
    if [ ! -d "wrs/patches" ]; then
	mkdir -p wrs/patches
    fi
    wrs_dir=wrs

    install_resources

    # turn guilt autoagging off, we don't use them manually and don't
    # want the tags floating around after we are done.
    #    correction: we need this for "refresh"
    # git config --global guilt.autotag 0

    # we don't want to commit any links to patches, so just exclude the
    # entire directory

    echo "# nothing to ignore" > wrs/.gitignore
    echo "*.patch" > wrs/patches/.gitignore
    echo "*.diff" >> wrs/patches/.gitignore
    if [ -e .gitignore ]; then
	cat .gitignore | sed s%^patches%#patches% | \
            sed s%^series%#series% > .gitignore.tmp
	mv .gitignore.tmp .gitignore
	echo "/LDAT_LINUX_PATCHES" >> .gitignore
	echo "/wrs" >> .gitignore
	git add .gitignore 
        git commit -m "gitignore: adding Wind River exclusions"
    else
	touch .gitignore
    fi

    echo "Initial creation marker" > .create_stamp
    git add -f .create_stamp
    git add -f .gitignore
    git commit -q -m "$message"

    # create a meta-information branch
    git branch wrs_meta

    # tag the Wind River base
    git tag "wrs_`date +%F`"
fi

if [ -n "$existing_repo" ]; then
    # this is an old repository, check if we should be restoring a checkpoint
    kgit-checkpoint -r
fi
