obj-$(CONFIG_WRHV_VIRTIO)	+= wrhv_devices.o
obj-$(CONFIG_WRHV_FRAME_TRANSITION_INTERRUPT_TEST) += wrhv_frame_irq.o
obj-$(CONFIG_WRHV_DUART)	+= wrhv_duart.o

obj-$(CONFIG_WRHV_VIRTIO_SERIAL) += wrhv_serial_driver.o

wrhv_serial_driver-objs	:= wrhv_serial.o wrhv_duart.o
